### ISSUE TITLE
UI Minor changes on Kost Detail

### ISSUE THREAD

**Issue by wahyubucil** [kostpedia/kostpedia-landing-page#27]
- Fix minimize button
- Price info should be left not center
- Truncate kost rules

**Comment by yawijaya** [comment]
Truncate kost rules tu apa ?

**Comment by wahyubucil** [comment]
Iya yg km suruh biar sama kayak di list kost itu textnya truncate namanya

**Comment by yawijaya** [comment]
owh, apalah daya aku taunya fadeout doang

okay lah, semangat
